= Basic Test of a multi-core application of safe-RTOS

== Overview

This sample application for safe-RTOS on the DEVKIT-MPC5748G demonstrates
the use of the kernel in a multi-core environment. All of the three cores
run safe-RTOS.

The kernel is started on the boot core Z4A. Here, the sample application
"basicTest" is configured, which we already know from the single core
installations of the RTOS. After starting the kernel the boot core
launches the second core.

The code on the second core, the Z4B, is the other sample application
"initial", i.e. one of the most simple possible task configurations with
two 1ms tasks (user mode and OS task), which simply drive an LED each and
which query the user buttons.

Both cores' applications use their specific LEDs, so that the concurrent
run of both the cores can be observed. Moreover, you are encouraged to
press the user buttons on the evaluation board and see if the related LEDs
are lit.

The code on the third core, the Z2, is similar to sample application
"initial". However, the use of LEDs and buttons is restricted. The only
LED, which is left, is driven by the idle task. The idle task implements a
watchdog for all other tasks and ISRs so that the LED will only blink if
everything is found to be alright.

== Cross-core notification service

This sample application introduces a new multi-core communication service.
Notifications can be sent from any to any core and a delivery acknowledge
can be got.

Notifications are basically events, which trigger a task on the
destination core, but they can carry a single 32 Bit word as argument,
too. If larger amounts of data need to be propagated with an event then
this is easily implementable because of the acknowledge mechanism. Shared
memory can be applied without any danger of race conditions.

The new driver is used on core Z2, which sends a notification to the Z4B.
There, task _taskNotificationFromZ2_ is executed each time the
notification is received.

The driver configuration is found locally as file
https://github.com/PeterVranken/DEVKIT-MPC5748G/blob/master/samples/safe-RTOS/code/application/triCore/icn_interCoreNotification.config.h[icn_interCoreNotification.config.h^]
and the driver implementation is found in the system files, see
https://github.com/PeterVranken/DEVKIT-MPC5748G/tree/master/samples/safe-RTOS/code/system/drivers/interCoreNotification/[^]

== Serial connection, progress output

Status and progress of the sample application are printed to the serial
port of the evaluation board. Open a terminal on the host machine to read
the output: 115200 Bd, 8 Bit, 1 Stop bit, no parity. Additionally, the
successfully running test can be observed by blinking LEDs on the board.
Five LEDs are permanently blinking at different rates and two of them
should be lit when pressing the user buttons. Only the eighth, innermost
mounted LED should never be alight: It would start blinking in case of a
problem recognized by the safety supervisor task on core Z4A.
