= CAN I/O Driver
:Author:            Peter Vranken
:Email:             mailto:Peter_Vranken@Yahoo.de[P. Vranken]
:Revision:          1
//:doctype:           book
:title-page:
//:table-caption:     Tabelle // TODO Extract all german label settings into new template
:toc:               left
//:toc-title:         Inhaltsverzeichnis
//:toc:
:toclevels:         3
//:numbered:
:xrefstyle:         short
//:sectanchors:       // Have URLs for chapters (http://.../#section-name
:icons:             font
:caution-caption:   :fire:
:important-caption: :exclamation:
:note-caption:      :paperclip:
:tip-caption:       :bulb:
:warning-caption:   :warning:
// https://asciidoctor.org/docs/user-manual/

== Overview

This folder contains a CAN communication I/O driver for MPC5748G and
safe-RTOS. Features:

* Support of one to eight available CAN devices (four on the MPC5775B/E)
* Pin configuration only for CAN device 0: On the PCB of the
  DEVKIT-MPC5748G, this one is equipped with a transceiver chip and connected
  to connector P5. Just connect your Vector, Kvaser or PEAK CAN device and
  run first tests
* The driver supports standard CAN
* Ease of use: One-by-one relation between mailboxes in the hardware and
  CAN ID. We have plenty of mailboxes so that sharing of mailboxes between
  different CAN IDs won't ever be required
* Rx FIFO can be enabled to further increase the number of mailboxes. We
  have a maximum of 96 to 186 mailboxes available per device, depending on
  how many are processed by the FIFO
 ** This number can even be increased to 276 if no extended CAN IDs are in
    use
 ** The maximum values are lesser by 32 for the MPC5775B/E
* Mailboxes can be operated by polling or by interrupt
 ** Mailboxes are organized in groups of 4, 8, 16 or 32. Each group can
    have its own interrupt - processed by the same or individual handlers,
    having same or different interrupt priority, processed on the same or
    on different cores
* Mailboxes have their individual privileges configuration. A mailbox can
  e.g. be dedicated to the safety process only. If so, a task from the QM
  process would neither be able to see the interrupt notification (if any)
  nor to use the polling or transmission APIs
* Configuration with compile-time expressions. Applying C99's designated
  initializer expressions, the readability and maintainability of the
  configuration file is pretty good

== Why don't we offer CAN FD?

Basically, CAN FD can be enabled by a few additional register
configurations and setting the enable bit. The complexity results from the
now inhomogeneous layout of the mailbox memory. For standard CAN it's
easy. All messages have a payload of 8 Byte and they form an array. For
FD, one has to decide how many message have 8 Byte size, how many have 16
Byte, etc. Defining a generic and easy to use API becomes more difficult
(both, run-time and compile-time configuration).

Moreover, the larger mailboxes together with the given size of available
memory reduce the number of mailboxes significantly, so that a driver
without some built-in buffering strategies may even be insufficient for
the client code. Such a strategy would mean a significant increase of the
required lines of code.

This CAN driver has been developed to operate not only on the MPC5748G but
it has been made also for the MPC5775B/E. This derivative has CAN devices,
which don't offer CAN FD at all.

Last but not least, we simply lack the experience with CAN FD. Having
never seen a true life CAN FD application so far (and nor an according
network configuration or DBC file) it's even more difficult to invent a
generic API for this use case.

== How to use

The driver has one principal header file,
https://github.com/PeterVranken/DEVKIT-MPC5748G/blob/master/samples/CAN/code/system/drivers/CAN/cdr_canDriverAPI.h[cdr_canDriverAPI.h^].
It contains the definition of the global interface of the CAN driver. Any
client code of the driver should normally not need definitions from other
header files - with the big exception of the definitions for the
compile-time configuration of the driver.

This header contains the data types and function prototypes to directly
use. Client code of the driver will solely include this header.
Nonetheless, this doesn't mean that this header file is self-contained.
It's not the encapsulation of an obscured driver implementation but
includes other nested headers, which still need to be available for
compilation of the client code.

The other relevant header file is cdr_canDriver.config.h. Client code
won't directly include it but you may need to open it for understanding
the configuration of the driver appropriately for your specific
application. The driver configuration is a large, nested constant data set
and this file documents all required fields.

The actual configuration is made in file cdr_canDriver.config.inc. This is
a hybrid from header and implementation file, that contains both,
declaration and definition of the configuration data object. The driver
implementation offers a template for this file, named
cdr_canDriver.config.inc.template.

The work flow is to make a copy of the template in the code repository of
the aimed application, using the original name cdr_canDriver.config.inc.
Then open the file and do all configuration according to the guiding
documentation and based on the sample configuration in the template. (And
based on the documentation in file cdr_canDriver.config.h.)

Actually, you specify the CAN driver configuration as a large initializer
expression of the one and only huge constant configuration data object.
This task is strongly facilitated by source code comments on the different
fields and by using C99's designated initializer expressions.

The principal element in configuration file cdr_canDriver.config.inc is
the list of #defines to enable one or more of the physically available CAN
devices; see e.g. #CDR_ENABLE_USE_OF_CAN_0. (Most applications won't use
all of them.) By means of preprocessor switches, the driver configuration
is produced only for the enabled set of devices (and alike for some
runtime data objects). Disabled CAN devices are not touched at all by the
driver and remain in reset state and nor do they consume ROM space for
configuration data.

Your application won't directly use the configuration file
cdr_canDriver.config.inc. Don't include it, don't compile it. Indirectly,
your application will read its header file contents (#define's) through
the principal header, cdr_canDriverAPI.h. Those parts of
cdr_canDriver.config.inc, which are actually C source code -- concretely,
the definition of the constant configuration data object, -- will be
compiled from the CAN driver's main implementation file, namely
cdr_canDriver.c, by way of including it.

The CAN driver is compilable with the renamed but not altered template
configuration file. However, no CAN device will then be enabled and the
compiler will issue several warnings because of zero-sized arrays and data
structures and useless conditional code.

== Maturity

Please note, the maturity of the driver implementation is not very high.
Concept and source code are on production level quality but the
implementation has not been tested accordingly. Even if not supporting all
features of the underlying hardware, the driver still offers a variety of
configuration possibilities. In the context of this project, it is
unfortunately not possible to develop tests for all imaginable reasonable
configurations.

If you decide to use this code you need to carefully test the driver
implementation in your configuration.

:Local Variables:
:coding:    utf-8
:End:
